---
- name: Configure a development laptop with Xfce4 using Ansible
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Configure dependencies, repositories and roles
      become: true
      tags:
        - always
      block:
        - name: Install dependencies
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
            update_cache: true
            install_recommends: false
          loop:
            - git
            - python3-debian
            - python3-lxml
            - python3-pip

        - name: Add Docker signing key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /usr/share/keyrings/docker-archive-keyring.asc
            mode: "0644"

        - name: Add Hashicorp signing key
          ansible.builtin.get_url:
            url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x798AEC654E5C15428C8E42EEAA16FCBCA621E701
            dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
            mode: "0644"

        - name: Add VirtualBox signing key
          ansible.builtin.get_url:
            url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xB9F8D658297AF3EFC18D5CDFA2F683C52980AECF
            dest: /usr/share/keyrings/virtualbox-archive-keyring.asc
            mode: "0644"

        - name: Add Docker repository
          ansible.builtin.deb822_repository:
            name: Docker
            types: deb
            uris: https://download.docker.com/linux/ubuntu
            architectures: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
            suites: "{{ ansible_distribution_release }}"
            components:
              - stable
            signed_by: /usr/share/keyrings/docker-archive-keyring.asc

        - name: Add Hashicorp repository
          ansible.builtin.deb822_repository:
            name: Hashicorp
            types: deb
            uris: https://apt.releases.hashicorp.com
            architectures: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
            suites: "{{ ansible_distribution_release }}"
            components:
              - main
            signed_by: /usr/share/keyrings/hashicorp-archive-keyring.asc

        - name: Add VirtualBox repository
          ansible.builtin.deb822_repository:
            name: VirtualBox
            types: deb
            uris: https://download.virtualbox.org/virtualbox/debian
            architectures: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
            suites: "{{ ansible_distribution_release }}"
            components:
              - contrib
            signed_by: /usr/share/keyrings/virtualbox-archive-keyring.asc

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true

    - name: Install and enable OpenVPN and Network Manager
      become: true
      tags:
        - vpn
      block:
        - name: Install OpenVPN and Network Manager
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
            update_cache: true
          loop:
            - network-manager
            - network-manager-gnome
            - network-manager-openvpn
            - openvpn
            - openvpn-systemd-resolved
            - python3-proton-vpn-network-manager-openvpn

        - name: Enable Network Manager
          ansible.builtin.systemd:
            name: NetworkManager
            enabled: true
            state: started
            daemon_reload: true

    - name: Add _proc group
      become: true
      ansible.builtin.group:
        name: _proc
        state: present
        gid: 2025

    - name: Import the hardening role
      ansible.builtin.import_role:
        name: konstruktoid.hardening
      tags:
        - hardening

    - name: Stat /etc/openvpn/client.conf
      become: true
      ansible.builtin.stat:
        path: /etc/openvpn/client.conf
      tags:
        - vpn
      register: openvpn_client_conf

    - name: Allow OpenVPN communications
      become: true
      when:
        - openvpn_client_conf.stat.exists
      tags:
        - vpn
      block:
        - name: Get OpenVPN remote servers
          become: true
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              echo "[$(grep -E 'remote\ [0-9]' /etc/openvpn/client.conf |\
                    awk '{print "{ \"ip\": \""$2"\", \"port\": "$3" },"}')]" |\
                    sed 's/,]/]/'
          changed_when: false
          register: openvpn_servers

        - name: Allow outgoing OpenVPN traffic
          community.general.ufw:
            rule: allow
            to_ip: "{{ item.ip }}"
            to_port: "{{ item.port }}"
            direction: out
            comment: ansible managed
          with_items:
            - "{{ openvpn_servers.stdout | from_json }}"

        - name: Allow traffic in on tap0
          community.general.ufw:
            rule: allow
            interface: tap0
            direction: in
            comment: ansible managed

        - name: Allow traffic out on tap0
          community.general.ufw:
            rule: allow
            interface: tap0
            direction: out
            comment: ansible managed

        - name: Enable OpenVPN
          ansible.builtin.systemd:
            name: openvpn
            enabled: true
            state: started
            daemon_reload: true

    - name: Install and configure the Xfce Desktop Environment
      tags:
        - xfce
      block:
        - name: Install Xfce4 with dependencies
          become: true
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
            update_cache: true
            install_recommends: false
          loop:
            - dbus-x11
            - xfce4
            - xinit
            - xorg

        - name: Set xfce4-session.xml path as fact
          ansible.builtin.set_fact:
            xfce4_session_xml_path: "{{ ansible_env.HOME }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml"

        - name: Stat xfce4-session.xml
          ansible.builtin.stat:
            path: "{{ xfce4_session_xml_path }}"
          register: xfce4_session_xml

        - name: Configure xfce4-session
          when:
            - not xfce4_session_xml.stat.exists
          block:
            - name: Create directory
              ansible.builtin.file:
                path: "{{ xfce4_session_xml_path | dirname }}"
                state: directory
                mode: "0700"

            - name: Copy xfce4-session.xml
              ansible.builtin.copy:
                remote_src: true
                src: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml"
                dest: "{{ xfce4_session_xml_path }}"
                mode: "0644"

        - name: Add security element
          community.general.xml:
            path: "{{ xfce4_session_xml_path }}"
            xpath: "/channel/property[@name='security']"
            attribute: type
            value: "empty"
            pretty_print: true

        - name: Add EnableTcp element
          community.general.xml:
            path: "{{ xfce4_session_xml_path }}"
            xpath: "/channel/property[@name='security']/property[@name='EnableTcp']"
            attribute: "{{ item.attr }}"
            value: "{{ item.value }}"
            pretty_print: true
          loop:
            - { attr: "type", value: "bool" }
            - { attr: "value", value: "false" }

    - name: Install developer tools
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - neovim
        - nodejs # GitHub Copilot requirement
        - docker-ce
        - lightdm
        - jq
        - slick-greeter
        - slirp4netns
        - tmux
        - uidmap
        - vagrant
        - vault
        - virtualbox

    - name: Add user to the docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user | default(lookup('ansible.builtin.env', 'USER')) }}"
        groups: docker
        append: true

    - name: Add users to the _proc group
      become: true
      ansible.builtin.user:
        name: "{{ item }}"
        groups: _proc
        append: true
      loop:
        - "{{ ansible_user | default(lookup('ansible.builtin.env', 'USER')) }}"
        - root

    - name: Clean up
      become: true
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        clean: true
        purge: true
