---
collections:
  - name: ansible.posix
    version: 2.1.0
    source: https://github.com/ansible-collections/ansible.posix.git
    type: git
  - name: community.crypto
    version: 3.0.3
    source: https://github.com/ansible-collections/community.crypto.git
    type: git
  - name: community.general
    version: 11.1.2
    source: https://github.com/ansible-collections/community.general.git
    type: git
roles:
  - name: konstruktoid.hardening
    version: v4.0.1
    src: https://github.com/konstruktoid/ansible-role-hardening.git
    scm: git
